=== EriJGS/documentosXML/ESPN.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/ESPN.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE partidos SYSTEM "ESPN.dtd">

    <partidos>
    ...
    </partidos>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT partidos (partido)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT partido (contricantes|ganador|anotaciones)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT contricantes (equipo1|equipo2)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT equipo1 (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT equipo2 (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ganador (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT anotaciones (anotacionesEquipo1|anotacionesEquipo2)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT anotacionesEquipo1 (#PCDATA)>
<!ATTLIST anotacionesEquipo1
    total CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT anotacionesEquipo2 (#PCDATA)>
<!ATTLIST anotacionesEquipo2
    total CDATA #IMPLIED
  >

=== EriJGS/documentosXML/ESPN.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE partidos SYSTEM "ESPN.dtd">

<!--
DESARROLLO III (27 de marzo de 2021) - Tarea: Desarrollo de documentos XML

En la sitio web espn.com.mx/futbol/resultados se muestran los resultados y estadísticas de los juegos de las diferentes
ligas de fútbol del mundo. Queremos contar con documento XML que permita representar los resultados de los partidos que
se jugaron en el torneo de la Liga BBVA MX.

Crear un documento XML para representar los resultados de una fecha en particular (e.g. Domingo 21 de Marzo 2021).
Validar que el documento esté bien formado (well formed). Interesa conocer: la fecha de los partidos, que equipos
se enfrentaron, el marcador final del encuentro, que jugadores anotaron y en que minuto del partido.

Crear el documento DTD para validar el documento XML con los resultados de los partidos.
-->

<partidos>
    <partido>
        <contricantes>
            <equipo1>Toluca</equipo1>
            <equipo2>Puebla</equipo2>   
        </contricantes>
        <ganador>Empate</ganador>
        <anotaciones>
            <anotacionesEquipo1 total="4">M Estrada(33',88'), P Canelo(54'PEN), Diego(78')</anotacionesEquipo1>
            <anotacionesEquipo2 total="4">S Ormeño(58'PEN), J Segovia(61'), D Aguilar(87'), D Álvarez(90')</anotacionesEquipo2>
        </anotaciones>
    </partido>
        
    <partido>
        <contricantes>
            <equipo1>Santos</equipo1>
            <equipo2>León</equipo2>
        </contricantes>
        <ganador>León</ganador>
        <anotaciones>
            <anotacionesEquipo1 total="1">F Gorriarán(32'PEN)</anotacionesEquipo1>
            <anotacionesEquipo2 total="2">Á Mena(24'PEN), F Navarro(59')</anotacionesEquipo2>
        </anotaciones>
    </partido>
</partidos>
